### ISSUE TITLE
AStages.addRestrictionForMod dynamic hiding/appearing fail

### ISSUE THREAD

**Issue by MisterZam27** [Alessandro-Casale/AStages#4]
I had a code where is I staged a whole mod. Once given the stage, it is no longer unfamiliar but it does not appear in the JEI

![image](https://github.com/user-attachments/assets/3bbf3b6d-3b35-4ca1-9dec-1c1abc8a1f8b)
There should be at least 3 pages worth of items from the mod Create: Steam 'n' Rails

**Comment by MisterZam27** [comment]
Actually, after tinkering around, all of the staged item does not dynamically appear once the stage is added. It needs to be forcefully reloaded to appear it in JEI. Is this a bug or it is working as intended?

**Comment by Alessandro-Casale** [comment]
Hi, can you please provide KubeJS code and logs?

**Comment by MisterZam27** [comment]
sure, here is the code

```js
console.info('The Factory Must Be Staged!')

ServerEvents.loaded(() => {
    AStages.addRestrictionForMod('astages/railways', 'Railway_Conductor', 'railways')
    .setHideInJEI(true)
    .setHideTooltip(true)
    .setRenderItemName(false)
    
    function stageItem (id, stage, item) {
        AStages.addRestrictionForItem('astages/'+id, stage, item)
        .setHideInJEI(true)
        .setHideTooltip(true)
        .setRenderItemName(false)
    }
    stageItem('sturdysheet', 'Railway_Conductor', 'create:sturdy_sheet')
    stageItem('railwaycasing', 'Railway_Conductor', 'create:railway_casing')
    stageItem('schedule', 'Railway_Conductor', 'create:schedule')
    stageItem('trackstation', 'Railway_Conductor', 'create:track_station')
    stageItem('tracksignal', 'Railway_Conductor', 'create:track_signal')
    stageItem('trackobserver', 'Railway_Conductor', 'create:track_observer')
    stageItem('controls', 'Railway_Conductor', 'create:controls')
    stageItem('traindoor', 'Railway_Conductor', 'create:train_door')
    stageItem('traintrapdoor', 'Railway_Conductor', 'create:train_trapdoor')
    stageItem('track', 'Railway_Conductor', 'create:track')
})

AStageEvents.added(event => {
    event.player.tell('You have unlocked '+event.getStage())
})
```

The log
[latest.log](https://github.com/user-attachments/files/17655636/latest.log)

**Comment by MisterZam27** [comment]
The log says it dynamically readded but not the case though hmm
Note: I am using JEI with EMI

**Comment by Alessandro-Casale** [comment]
At present (8/11/2024) **EMI does not support** the ability to hide and add items at runtime, so if you want to use any staging mod, you need to use JEI or REI with JEI plugin. Sorry for the inconvenience.
