### ISSUE TITLE
Warning not disappearing from the screen 

### ISSUE THREAD

**Issue by Mainali1** [Alessandro-Casale/AStages#5]
![image_2024-12-16_175347772](https://github.com/user-attachments/assets/8bdd56b8-7ef9-4c9e-86ac-474270111213)
 Hello I am having issues with astages so i mistakely tried to mine the block whose stage i havent unlocked and now i am getting this message for the whole time is there any way to fix it ?

**Comment by Alessandro-Casale** [comment]
Solved in 0.6.1 update!
